name: hotspot
description: Easy product tours.
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
